# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d38c7bb8c7f5d4f0d1b5062e75a4fed20cd7b7d1f86baa053ab03ca50810f9d4689a3f0d1eedaf666b1d2c39b488800a5777dd83a2a092bd56fc7a8f2a7348d

test:
  secret_key_base: b0dee05159757d9474c79a627a14c1c3362ae32c725f687608d4b7ea323e0a22d512a25b2db31652cc95ea55de7e8d06d14cb556fb2eef50da0cbbd33fb1511d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
